build: off
deploy: off

clone_folder: C:\arduino-cli
shallow_clone: true

skip_tags: true
skip_branch_with_pr: true

environment:
  GOPATH: c:\gopath
  PROTOC_PATH: c:\protoc
  # add protoc, gopath and override default Python 2.7
  PATH: $(PROTOC_PATH)\bin;$(GOPATH)\bin;C:\Python37;C:\Python37\Scripts;$(PATH)

stack: go 1.12

install:
  # install the task executor
  - curl -o task.zip -LO https://github.com/go-task/task/releases/download/v2.6.0/task_windows_amd64.zip
  - 7z e task.zip -o%GOPATH%\bin
  # golang dependencies needed at test time
  - go get github.com/golangci/govet
  - go get golang.org/x/lint/golint
  # Python dependencies needed at test time
  - python -V
  - pip install -r test\requirements.txt
  # protobuf tooling needed at test time
  - go get github.com/golang/protobuf/protoc-gen-go
  - curl -o protoc.zip -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.8.0/protoc-3.8.0-win64.zip
  - 7z e protoc.zip -o%PROTOC_PATH%

test_script:
  # Check if the Go code is properly formatted and run the linter
  - task.exe check
  # Ensure protobufs compile
  - task.exe protoc
  # re-enable after fixing go tests
  # - task.exe test-integration
  # build the binary
  - task.exe build
  # run e2e tests
  - pytest test

# uncomment to debug builds
on_finish:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))