version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
    default_labels:
      - "topic: dependencies"
