name: docs

on:
  pull_request:
    paths:
      # existing docs
      - 'docs/**'
      # changes to the cli reference generator
      - 'docsgen/**'
      # potential changes to commands documentation
      - 'cli/**'
      # potential changes to gRPC documentation
      - 'rpc/**'
  push:
    branches:
      - master
      # release branches have names like 0.8.x, 0.9.x, ...
      - '[0-9]+.[0-9]+.x'
    # At this day, GitHub doesn't support YAML anchors, d'oh!
    paths:
      - 'docs/**'
      - 'docsgen/**'
      - 'cli/**'
      - 'rpc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REMOTE: https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14'

      - name: Install Go dependencies
        run: |
          go version
          go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: Install protoc compiler
        uses: arduino/setup-protoc@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements_docs.txt

      - name: Build docs website
        # this runs on every PR to ensure the docs build is sane
        if: github.event_name == 'pull_request'
        run: task docs:build

      - name: Publish dev docs
        # dev docs are published every time a commit is pushed to master
        if: github.event_name == 'push' && github.ref == 'master'
        run: task docs:publish DOCS_REMOTE=$REMOTE DOCS_VERSION=dev

      - name: Publish versioned docs
        # versioned docs are published every time a commit is pushed to
        # a release branch
        if: github.event_name == 'push' && github.ref != 'master'
        run: task docs:publish DOCS_REMOTE=$REMOTE DOCS_VERSION=${{github.ref}}
