name: "Mirror new issue to Jira for grooming"

on:
  issues:
    types: [opened, labeled]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    if: >
      github.event.action == 'opened' &&
      !contains(github.event.issue.labels.*.name, 'tracked')

    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}

    steps:
      - name: Installs Jira CLI
        uses: atlassian/gajira-cli@master
        with:
          version: 1.0.23

      - name: Writes Jira CLI configs
        run: |
          mkdir ~/.jira.d
          cat <<EOM >~/.jira.d/config.yml
          endpoint: ${{ secrets.JIRA_BASE_URL }}
          user: ${{ secrets.JIRA_USER_EMAIL }}
          authentication-method: api-token
          EOM

      - name: Create issue
        run: |
          jira create \
          --noedit \
          -p ${{ secrets.JIRA_PROJECT_CODE }} \
          -i Task \
          -o summary="$ISSUE_TITLE" \
          -o description="$ISSUE_BODY
          ${{ github.event.issue.html_url }}" \
          >> output

      - name: Set label on Jira issue
        run: |
          jira labels add \
          $(cat output | awk '{split($0,a," "); print a[2]}') \
          grooming arduino-cli

      - name: Set label on Github issue
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['tracked']
            })

  label-issue:
    runs-on: ubuntu-latest

    if: >
      (github.event.issue.author_association == 'OWNER' ||
      github.event.issue.author_association == 'COLLABORATOR' ||
      github.event.issue.author_association == 'MEMBER') &&
      github.event.action == 'labeled' &&
      github.event.label.name == 'tracked'

    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}

    steps:
      - name: Installs Jira CLI
        uses: atlassian/gajira-cli@master
        with:
          version: 1.0.23

      - name: Writes Jira CLI configs
        run: |
          mkdir ~/.jira.d
          cat <<EOM >~/.jira.d/config.yml
          endpoint: ${{ secrets.JIRA_BASE_URL }}
          user: ${{ secrets.JIRA_USER_EMAIL }}
          authentication-method: api-token
          EOM

      - name: Create issue
        run: |
          jira create \
          --noedit \
          -p ${{ secrets.JIRA_PROJECT_CODE }} \
          -i Task \
          -o summary="$ISSUE_TITLE" \
          -o description="$ISSUE_BODY
          ${{ github.event.issue.html_url }}" \
          >> output

      - name: Set label on Jira issue
        run: |
          jira labels add \
          $(cat output | awk '{split($0,a," "); print a[2]}') \
          grooming arduino-cli
